---
version: "2"

services:
  mongo:
    image:
      mongo:3

  elasticsearch:
    image:
      docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    image:
      graylog/graylog:2.4
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    links:
      - mongo
      - elasticsearch
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI=http://graylog:9000/api
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
